create table races(race_id serial primary key,
 race_name varchar(80),
  size varchar(1),
   speed varchar(40),
    languages varchar(80),
     vision varchar(80),
      strength int,
       dexterity int,
        constitution int,
         intelligence int,
          wisdom int,
           charisma int)
         insert into races(race_name,
  size,
   speed,
    languages,
     vision,
      strength,
       dexterity,
        constitution,
         intelligence,
          wisdom,
           charisma )  values(
               'Human',
               'M',
               '30 feet',
               'common, Bonus',
               'light',
               0,
               0,
               0,
               0,
               0,
               0

           )
                    insert into races(race_name,
  size,
   speed,
    languages,
     vision,
      strength,
       dexterity,
        constitution,
         intelligence,
          wisdom,
           charisma )
values('Dwarf', 'M', '20 feet', 'common, Dwarven', 'DarkVision', 0, 0, 2, 0, 0, -2)
