create table skill_list(skill_id serial primary key,
 skill_name varchar(40),
  skill_Key_ability varchar(40),
   Untrained boolean,
 Armor_penalty boolean,
 description varchar(40))
 insert into skill_list(skill_name, skill_key_ability, Ability_id, untrained, armor_penalty, description)
values('Appraise', 'int',3, true, false, 'Approximating value of items'),
('balance', 'dex',1, true, false, 'Keeping yourself from falling on precarious terrain'),
('Bluff', 'cha',5, true, false, 'Lying in any way, shape or form'),
('Climb', 'str',0, true, true, 'Scaling anything from cliffs to walls'),
('Concentration', 'con',2, true, false, 'Focus on Something, usually spells you are casting'),
('Craft', 'int',3, false, false, 'To create something from materials.'),
('Decipher Script', 'int',3, false, false, 'An attempt to crack written codes'),
('Diplomancy', 'cha',5, true, false, 'Attempting to convey your point or persuade someone'),
('Disable Device', 'dex',1, false, false, 'The art of dismantling traps of mechanical type'),
('Disguise', 'cha',5, true, false, 'An attempt to hide your identity, or temporarily act as another'),
('Escape Artist', 'dex',1, false, false, 'Useful for escaping the grasp others'),
('Forgery', 'int',3, true, false, 'The art of crafting documents that look as if it is someone elses'),
('Gather Information', 'Cha',5, true, false, 'The skill of finding info in town'),
('Handle Animal', 'Cha',5, true, false, 'An attempt to calm a wild animal'),
('Heal', 'Wis',4, true, false, 'The art of healing with sterilization, and other healing techniques'),
('Hide', 'Dex',1, true, false, 'The art of fading into the shadows, and not being noticed'),
('Intimidate', 'Cha',5, true, false, 'The ability to compel others into doing what you say')
insert into skill_list(skill_name, skill_key_ability, Ability_id, untrained, armor_penalty, description)
values('Jump', 'str',0, true, true, 'How high or far you can jump'),
('Knowledge', 'int',3, true, true,'General education and recalling this knowledge'),
('Listen', 'wis',4, true, false, 'paying attention to speech or any other sound'),
('Move Silently', 'dex', 1,true, false, 'The attempt to move without being discovered.'),
('Open Lock', 'dex', 1, false, false, 'the art of picking locks'),
('Perform', 'cha',5, true, false, 'an attempt to do a kinetic or musical performance'),
('Ride', 'dex', 1, true, false, 'the skill of riding animals or magical beasts'),
('Search','int', 3, true, false,'Looking for anything'),
('Sense Motive', 'cha',5, true, false,'An attempt to understand motives of someone who is speaking to you, and know if they are lying or hiding info.'),
('Sleight Of Hand', 'Dex',1,true, false,'any dexterous hand movement such as stacking a deck of cards or moving a shell in cups quickly, or even pickpocketing'),
('SpellCraft', 'int',3, true, false, 'An attempt to understand magicks stored in items or walls'),
('Spot', 'wis',4, true, false, 'To look for movement in the distance or see an object from far away'),
('Survival', 'wis',4, true, false, 'An attempt to build fires, harvest food, hunt, or detect poison before ingesting'),
('Tumble', 'dex', 1, true, true, 'To roll away from enemies or harm'),
('Use Magic Device', 'Cha', 5, true, false,'an attempt to coerce magical items to activate'),
('Use Rope', 'dex',1, true, false, 'The art of knots and tying')
